import { ILocals } from './Locals';
export const ArabicLocals: ILocals = {
    close: 'اغلاق',
    home: 'الرئيسية',
    about_us: 'من نحن',
    contact_us: 'تواصل معنا',
    destinations: 'وجهات سياحية',
    services: 'الخدمات',
    partners: 'الشركاء',
    email: 'البريد الالكتروني',
    message: 'الرسالة',
    name: 'الاسم',
    send: 'ارسال',
    subject: 'الموضوع',
    price: 'السعر',
    description: 'التفاصيل',
    duration: 'المدة',
    for_booking: 'للحجز',
    images: 'الصور',
}